services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - "5432:5432"
    expose:
      - "5432"
  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
    expose:
      - "6379"
  rabbitmq:
    image: "rabbitmq:3.8.6-management"
    container_name: rabbitmq-event-ticket
    ports:
      - 5672:5672
      - 15672:15672

