apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway-app
          image: event-ticket-application_apigateway
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: app-env
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
spec:
  selector:
    app: apigateway
  ports:
    - port: 80
      targetPort: 8081
  type: LoadBalancer