apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  uri: bW9uZ29kYitzcnY6Ly9TYXVsbzp2TUdTVFlHMVNadUswZEBjbHVzdGVyMC5yc3ZxZ2xjLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyMA==
  database: ZXZlbnRfZGF0YQ==
