apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-processor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-processor
  template:
    metadata:
      labels:
        app: payment-processor
    spec:
      containers:
        - name: payment-app
          image: event-ticket-application_payment
          ports:
            - containerPort: 8083
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://discovery-service:8761/eureka/"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: secret-key
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: webhook-secret
---
apiVersion: v1
kind: Service
metadata:
  name: payment-processor-service
spec:
  selector:
    app: payment-processor
  ports:
    - port: 8083
      targetPort: 8083