apiVersion: apps/v1
kind: Deployment
metadata:
  name: recomendation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recomendation
  template:
    metadata:
      labels:
        app: recomendation
    spec:
      containers:
        - name: recomendation-app
          image: saul97arch/event-ticket-application_recomendation
          ports:
            - containerPort: 8082
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://discovery-service:8761/eureka/"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: uri
            - name: MONGO_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: database
---
apiVersion: v1
kind: Service
metadata:
  name: recomendation-service
spec:
  selector:
    app: recomendation
  ports:
    - port: 8082
      targetPort: 8082